site_name: Lokesh angular documentation 
nav:
 - Home: index.md
 - Basics Topics In Angular : Basics.md
 - Java Script String Methods : stringmethods.md
 - Java Script Array Methods : Arraymethods.md
 - Java Script Object Methods : objectmethods.md
 - Single and 2 way Binding : dataBinding.md
 - Input And Output Binding : input$output.md
 - Ngconent&Ngtemplate&Ngcontainer&Viewencapsulation : ngconent&ngtemplate&ngcontainer&viewencapsulation.md
 - Directives : directives.md
 - Pipes&Custompipes : pipes.md
 - Customdirectives : customdirectives.md

theme:
  name: material